version: '3.0'

services:
  demo1:
    build:
      context: ./demo1
    container_name: demo1
    ports:
      - "8081:8080"
    volumes:
      - ./demo1:/app
      - ~/.m2:/root/.m2
    networks:
      - app-network
  demo2:
    build:
      context: ./demo2
    container_name: demo2
    ports:
      - "8082:8080"
    volumes:
      - ./demo2:/app
      - ~/.m2:/root/.m2
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - demo1
      - demo2
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge